name: Yet another Lint

permissions:
  contents: read
  packages: read
  statuses: write
  
on:
  workflow_dispatch:
    inputs:
      default-branch:
        required: false
        type: string
        description: "default branch of the repository"
        default: main

jobs:
  perform_lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6.6.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
